
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 25 08:08:05 CST 2015
//----------------------------------------------------

package lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 44;
  public static final int DIVEQ = 31;
  public static final int GTEQ = 20;
  public static final int SCANF = 10;
  public static final int MULT = 47;
  public static final int CHAR = 8;
  public static final int LTEQ = 21;
  public static final int LPAREN = 36;
  public static final int INT = 49;
  public static final int MINUS = 46;
  public static final int FOR = 4;
  public static final int SFLAG = 14;
  public static final int RPAREN = 37;
  public static final int OROR = 22;
  public static final int NOT = 24;
  public static final int SEMICOLON = 32;
  public static final int AND = 26;
  public static final int LT = 19;
  public static final int OR = 25;
  public static final int COMMA = 33;
  public static final int DFLAG = 13;
  public static final int DIV = 48;
  public static final int ANDAND = 23;
  public static final int PLUSEQ = 28;
  public static final int MINUSEQ = 29;
  public static final int PLUS = 43;
  public static final int MAIN = 50;
  public static final int IF = 2;
  public static final int Number = 51;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 45;
  public static final int RETURN = 6;
  public static final int error = 1;
  public static final int EQEQ = 17;
  public static final int CONSTSTR = 40;
  public static final int MULTEQ = 30;
  public static final int BREAK = 12;
  public static final int VOID = 7;
  public static final int EQ = 27;
  public static final int CFLAG = 15;
  public static final int PRINTF = 11;
  public static final int LBRACK = 38;
  public static final int LBRACE = 34;
  public static final int ELSE = 3;
  public static final int RBRACK = 39;
  public static final int WHILE = 5;
  public static final int RBRACE = 35;
  public static final int STRING = 9;
  public static final int CONSTCHAR = 41;
  public static final int GT = 18;
  public static final int NOTEQ = 16;
  public static final int IDENTIFIER = 42;
}

